<?php
use App\service\Container;
use App\Controller\accounts\LoginUser;
use App\Controller\authordash\ListBook;
use App\Controller\authordash\SalesReport;
use App\Controller\orders\OrderConfirm;
use App\Controller\accounts\RegisterUser;
use App\Controller\accounts\Forget;
use App\Controller\authordash\AuthorWelcomePage;
use App\Controller\authordash\BecomeUser;
use App\Controller\authordash\DeleteBook;
use App\Controller\authordash\EditBook;
use App\Controller\authordash\publishPlatformController;
use App\Controller\authordash\UpdateBook;
use App\Controller\home\bookdetails;
use App\Controller\home\categoryController;
use App\Controller\home\SearchByTitle;
use App\Controller\orders\checkout;
use App\Controller\UserDash\BecomeAuthor;
use App\Controller\UserDash\editprofile;
use App\Controller\UserDash\RecentOrder;
use App\Controller\UserDash\UpdateProfile;
use App\Controller\accounts\Forgetform;
use App\Controller\accounts\Loginform;
use App\Controller\accounts\Registerform;
use App\Controller\accounts\chooseRole;
use App\Controller\UserRedirect;
use App\Controller\accounts\Logout;
use App\Controller\authordash\CreateBookForm;
use App\Controller\home\Firsts;
use App\Controller\UserDash\WelcomeUser;

$value = array();

$container = new Container();

$routes = new routes();

$home = $container->get(Firsts::class);
$loginuser = $container->get(LoginUser::class);
$registerUser = $container->get(RegisterUser::class);
$forgetuser = $container->get(Forget::class);
$welcome = $container->get(AuthorWelcomePage::class);
$deletebook = $container->get(DeleteBook::class);
$listbook = $container->get(ListBook::class);
$salesreport = $container->get(SalesReport::class);
$updatebook = $container->get(UpdateBook::class);
$publishBook = $container->get(publishPlatformController::class);
$editbook = $container->get(EditBook::class);
$becomeUser = $container->get(BecomeUser::class);
$bookdetails = $container->get(bookdetails::class);
$checkout = $container->get(checkout::class);
$category = $container->get(categoryController::class);
$searchbook = $container->get(SearchByTitle::class);
$recentorder = $container->get(RecentOrder::class);
$editprofile = $container->get(editprofile::class);
$updateprofile = $container->get(UpdateProfile::class);
$becomeAuthor = $container->get(BecomeAuthor::class);
$orderconfirm = $container->get(OrderConfirm::class);
$logout = $container->get(Logout::class);
$forgetform = $container->get(Forgetform::class);
$registerform = $container->get(Registerform::class);
$loginform = $container->get(Loginform::class);
$chooserole = $container->get(chooseRole::class);
$userredirect = $container->get(UserRedirect::class);
$createbookform = $container->get(CreateBookForm::class);
$userwelcome = $container->get(WelcomeUser::class);

$routes->addRoute(new Route("/",$home,"displayBook",$value));
$routes->addRoute(new Route("/login",$loginuser,"inputData",$_POST));
$routes->addRoute(new Route("/register",$registerUser,"inputData",$_POST));
$routes->addRoute(new Route("/forget",$forgetuser,"inputData",$_POST));
$routes->addRoute(new Route("/welcomeauthor",$welcome,"welcomeAuthordash",$_POST));
$routes->addRoute(new Route("/deletebook",$deletebook,"deletedBookController",$_GET));
$routes->addRoute(new Route("/listbook",$listbook,"listBookManager",$value));
$routes->addRoute(new Route("/salesreport",$salesreport,"salesReportController",$value));
$routes->addRoute(new Route("/updatebook",$updatebook,"inputData",$_POST));
$routes->addRoute(new Route("/publishbook",$publishBook,"inputData",$_POST));
$routes->addRoute(new Route("/editbook",$editbook,"editBookController",$_GET));
$routes->addRoute(new Route("/becomeuser",$becomeUser,"becomeUserController",$value));
$routes->addRoute(new Route("/bookdetails",$bookdetails,"findBook",$_GET));
$routes->addRoute(new Route("/checkout",$checkout,"checkoutcontroller",$_POST));
$routes->addRoute(new Route("/category",$category,"findBook",$_GET));
$routes->addRoute(new Route("/searchbook",$searchbook,"findBook",$_GET));
$routes->addRoute(new Route("/recentorder",$recentorder,"executeAction",$value));
$routes->addRoute(new Route("/editprofile",$editprofile,"executeAction",$value));
$routes->addRoute(new Route("/updateprofile",$updateprofile,"executeAction",$_POST));
$routes->addRoute(new Route("/becomeauthor",$becomeAuthor,"executeAction",$value));
$routes->addRoute(new Route("/orderconfirm",$orderconfirm,"ordersConfirmController",$_POST));
$routes->addRoute(new Route("/loginform",$loginform,"loginFormController",$value));
$routes->addRoute(new Route("/registerform",$registerform,"registerFormController",$value));
$routes->addRoute(new Route("/forgetform",$forgetform,"forgetFormController",$value));
$routes->addRoute(new Route("/logout",$logout,"logoutController",$value));
$routes->addRoute(new Route("/userredirect",$userredirect,"userRedirectController",$value));
$routes->addRoute(new Route("/chooserole",$chooserole,"chooseRoleController",$value));
$routes->addRoute(new Route("/createbookform",$createbookform,"createBookFormController",$value));
$routes->addRoute(new Route("/userwelcome",$userwelcome,"welcomeUserController",$value));


return $routes;